site_name: Ahmed's Second Brain
site_author: Ahmed Bay
copyright: Copyright &copy; 2026 Ahmed Bay
site_url: https://itsbayahmed.github.io/
repo_url: https://github.com/itsbayahmed/itsbayahmed.github.io
edit_uri: edit/main/docs

theme:
  name: material
  palette:
    # Light Mode Setting
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark Mode Setting
    - scheme: slate
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.expand
    - content.code.copy
nav:
  - Home: index.md
  - 'Linux Ricing':
    - 'Fedora Setup': linux/fedora-after-install.md


